config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "samples#top"
  resources :samples, only: [:index, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  def top
  end

  def index
    @sample = Sample.new
    @samples = Sample.all

    puts "作成した環境変数#{ENV["SECRET_KEY"]}"
  end

  def create
    @sample = Sample.new(sample_params)
    @sample.save
    redirect_to sample_path(@sample.id)
  end

  def show
    @sample = Sample.find(params[:id])
    @samples = Sample.new
  end

  private

  def sample_params
    params.require(:sample).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_app.html.erb
<script>
var hello = "hello";
var world = "world";
var number = (3+5);
alert(hello+world+number)

var orange = 100;
var apple = 90;
if(orange < apple){
  alert("オレンジはリンゴより安い");
}else if (orange == apple){
  alert("オレンジとリンゴは同じ値段");
}else {
  alert("オレンジの方がリンゴより高い")
}

var max = 10000;
var num = 1;
var count = 0;
while(num<max){
  num = num+2;
  count = count+1;
}
alert("2を足し続けて"+max+"を超えるためには"+count+"回足し続ける必要がある.")

var i;
var num = 0;
for(i=1;i<11;i++){
  num = num+i;
}
alert("１から１０まで足し算した結果は"+num+"です。")


var alertString;
alertString = addString("webcamp");

alert(alertString);

function addString(strA){
  var addStr = "hello" + strA;
  return addStr;
}

var PromptStr = prompt("今の気分を書いてね");
alert(PromptStr);


var user_hand = prompt("グー・チョキ・パーからえらんでにょ");
var js_hand = getJShand();
var judge = WinLose(user_hand, js_hand);
alert("あなたの選んだ手は"+user_hand+"です。Javascriptが選んだ手は"+js_hand+"です。結果は"+judge+"だぜ。")


function getJShand(){
  var js_hand_num = Math.floor(Math.random()*3);
  var hand_name

  if (js_hand_num == 0){
    hand_name = "グー";
  }else if (is_hand_num == 1){
    hand_name = "チョキ";
  }else if (js_hand_num == 2){
    hand_name = "パー";
  }
 return hand_name;
}

function WinLose(user,js){
var WinLoseStr;

if (user == "グー"){
  if (js == "グー"){
    WinLoseStr = "あいこ";
  }else if (js == "チョキ"){
    WinLoseStr = "勝ち！";
  }else if (js == "パー"){
    WinLoseStr = "負けとか、ぷぷ、、、";
  }
}else if (user == "チョキ"){
  if (js == "グー"){
    WinLoseStr = "負けかよ、次に期待してるよ";
  }else if (js == "チョキ"){
    WinLoseStr = "あいこだ！惜しいな";
  }else if (js == "パー"){
    WinLoseStr = "勝ちやで！！やるやん";
  }
}else if (user == "パー"){
  if (js == "グー"){
    WinLoseStr = "勝ったやん、おごりな";
  }else if (js == "チョキ"){
    WinLoseStr = "負けかよ期待しちまったわ";
  }else if (js = "パー"){
    WinLoseStr = "あいこよ;"
  }
}
return WinLoseStr;
}

</script>

app/views/samples/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">

      <h1>投稿フォーム</h1>
        <%= form_with model: @sample, local: true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>body</h4>
        <%= f.text_area :body, cols: "30", rows: "3" %>
        <%= f.submit "投稿" %>
          <% end %>
    </div>
    <div class="col-md-8" "offset-1">
      <h1>投稿一覧</h1>
      <table class= "table table-dark">
        <thead>
          <tr>
            <th>title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @samples.each do |sample| %>
        <thead>
          <tr>
           <td>title:<%=link_to sample.title, sample_path(sample.id) %></td>
           <td>body:<%=sample.body %></td>
          </tr>
        </thead>
        <% end %>
      </table>
    </div>
  </div>
</div>

<%= link_to "トップへ戻る", root_path, class:"btn btn-success" %>

app/views/samples/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">

      <h1>投稿フォーム</h1>
        <%= form_with model: @samples, local: true do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>body</h4>
        <%= f.text_area :body %>
        <%= f.submit "投稿" %>
          <% end %>
    </div>
    <div class="col-md-8" "offset-1">
      <h1>投稿一覧</h1>
      <table class= "table table-dark">
        <thead>
          <tr>
            <th>title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <thead>
          <tr>
            <td><%=@sample.title %></td>
            <td><%=@sample.body %></td>
          </tr>
        </thead>
      </table>
      <%= link_to "一覧へ", samples_path, class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/samples/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
  </head>
  <body>

    <%= render "app" %>

    <h1>ようこそ！！</h1>
    <%= link_to "index", samples_path, class:"btn btn-success" %>

  </body>
</html>